resolver: lts-16.16
#resolver: lts-12.0


packages:
- .

extra-deps:
  - snap-1.1.3.1
  - heist-1.1.0.1
  - map-syntax-0.3
  - pwstore-fast-2.4.4
  - xmlhtml-0.2.5.2
#  - Spock-0.13.0.0
#  - Spock-core-0.13.0.0
#  - reroute-0.5.0.0